language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

install:
  - npm install

script: 
  - npm test

after_success:
  - npm run build

deploy:
  provider: firebase
  token: $FIREBASE_AUTH_TOKEN
  skip_cleanup: true
